# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('pub_source', models.TextField()),
                ('fingerprint', models.TextField()),
                ('buy_vote_count', models.IntegerField(default=0)),
                ('sell_vote_count', models.IntegerField(default=0)),
                ('hold_vote_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'news',
                'managed': True,
            },
        ),
    ]
