# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.TextField()),
                ('user_token', models.TextField()),
                ('fingerprint', models.TextField()),
                ('vote_type', models.TextField()),
            ],
        ),
    ]
