# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactOpinionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.TextField()),
                ('user_token', models.TextField()),
                ('fingerprint', models.TextField()),
                ('vote_type', models.TextField(default='neutral')),
            ],
        ),
        migrations.CreateModel(
            name='TradeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.TextField()),
                ('user_token', models.TextField()),
                ('fingerprint', models.TextField()),
                ('vote_type', models.TextField(default='neutral')),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='news',
            name='fact_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='opinion_vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
