# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170928_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='down_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='news',
            name='up_vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
