# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_updownvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
